### Задача 1

Напишите функцию, которая находит сумму квадратов положительных элементов одномерного массива.

In [ ]:
import random

import numpy as np

In [2]:
array = np.random.randint(-100, 100, 10)
print(array)

def get_squares(array):
    return sum(array[array > 0] ** 2)

print(get_squares(array))

[  85   66  -48   72   55 -100  -56  -36    0   70]
24690


### Задача 2

Коля – мастер покера и умеет выигрывать только целые суммы денег от 0 до n - 1. Коля решил сыграть на турнире. На вход подаётся массив p размера n, где p[i] – вероятность, что Коля выиграет на турнире i рублей (∑ n i=1 pi=1, pi⩾0,∀i). Посчитайте математическое ожидание выигрыша Коли на турнире.

# 🎯 Подробный разбор задачи: Математическое ожидание выигрыша

## 📚 Часть 1: Суть задачи простыми словами

Представьте, что Коля играет в покер на турнире. У него есть **n возможных исходов**:
- Он может выиграть **0 рублей**
- Он может выиграть **1 рубль**
- Он может выиграть **2 рубля**
- ...
- Он может выиграть **(n-1) рублей**

Для каждого исхода нам известна **вероятность** — число от 0 до 1, которое показывает, насколько этот исход возможен.

**Что нужно найти?**
Нужно найти **средний выигрыш** Коли, если бы он сыграл на таком турнире **бесконечно много раз**.

> 💡 **Интуиция:** Математическое ожидание — это "справедливая" или "средняя" сумма, которую Коля будет получать за одну игру в долгосрочной перспективе.

---

## 🧮 Часть 2: Математическая основа

### Что такое математическое ожидание?

Для **дискретной случайной величины** (как в нашем случае, где выигрыш может быть только целым числом) формула выглядит так:

$$E[X] = \sum_{i} x_i \cdot P(X = x_i)$$

Где:
- $X$ — случайная величина (выигрыш Коли)
- $x_i$ — возможные значения (0, 1, 2, ..., n-1)
- $P(X = x_i)$ — вероятность каждого значения
- $E[X]$ — математическое ожидание (то, что мы ищем)

### Применяем к нашей задаче:

В нашем случае:
- Возможные выигрыши: $x_i = i$ (индекс совпадает со значением!)
- Вероятности: $P(X = i) = p[i]$

Подставляем в формулу:

$$E[X] = 0 \cdot p[0] + 1 \cdot p[1] + 2 \cdot p[2] + \ldots + (n-1) \cdot p[n-1]$$

Или в компактной записи:

$$E[X] = \sum_{i=0}^{n-1} i \cdot p[i]$$

---

## 🔍 Часть 3: Разбор на конкретном примере

Давайте возьмем конкретный пример, чтобы всё стало кристально ясно.

**Дано:**
```
n = 4
p = [0.1, 0.3, 0.2, 0.4]
```

**Что это значит?**
- С вероятностью **0.1** (10%) Коля выиграет **0 рублей**
- С вероятностью **0.3** (30%) Коля выиграет **1 рубль**
- С вероятностью **0.2** (20%) Коля выиграет **2 рубля**
- С вероятностью **0.4** (40%) Коля выиграет **3 рубля**

**Проверка:** 0.1 + 0.3 + 0.2 + 0.4 = 1.0 ✅ (сумма вероятностей равна 1)

### Считаем математическое ожидание вручную:

| Выигрыш (i) | Вероятность p[i] | Произведение i × p[i] |
|-------------|------------------|----------------------|
| 0           | 0.1              | 0 × 0.1 = **0.0**    |
| 1           | 0.3              | 1 × 0.3 = **0.3**    |
| 2           | 0.2              | 2 × 0.2 = **0.4**    |
| 3           | 0.4              | 3 × 0.4 = **1.2**    |

**Суммируем:**
$$E[X] = 0.0 + 0.3 + 0.4 + 1.2 = 1.9$$

**Ответ:** В среднем Коля будет выигрывать **1.9 рубля** за турнир.

---

## 🧠 Часть 4: Интуитивное понимание (зачем это нужно?)

Представьте, что Коля сыграл на **100 таких турнирах**. Сколько он выиграет суммарно?

Исходя из вероятностей:
- 10 раз он выиграет 0 рублей → 10 × 0 = 0 рублей
- 30 раз он выиграет 1 рубль → 30 × 1 = 30 рублей
- 20 раз он выиграет 2 рубля → 20 × 2 = 40 рублей
- 40 раз он выиграет 3 рубля → 40 × 3 = 120 рублей

**Суммарный выигрыш:** 0 + 30 + 40 + 120 = **190 рублей**

**Средний выигрыш за турнир:** 190 / 100 = **1.9 рубля** ✅

Именно это число мы и получили через формулу математического ожидания!

---

## 💻 Часть 5: Реализация на Python

### Вариант 1: Без NumPy (обычный цикл)

Самый простой и понятный способ — использовать обычный цикл:

```python
n = int(input())
p = list(map(float, input().split()))

expected_value = 0
for i in range(n):
    expected_value += i * p[i]

print(expected_value)
```

**Как это работает:**
1. Считываем `n` — количество возможных выигрышей
2. Считываем массив `p` — вероятности
3. Проходим циклом от 0 до n-1
4. На каждом шаге умножаем индекс `i` на вероятность `p[i]` и добавляем к сумме
5. Выводим результат

### Вариант 2: С использованием NumPy (векторный подход)

NumPy позволяет делать те же операции **гораздо быстрее** и **короче**:

```python
import sys
import numpy as np

def solve():
    data = sys.stdin.read().split()
    if not data:
        return
        
    n = int(data[0])
    p = np.array(data[1:n+1], dtype=float)
    
    winnings = np.arange(n)
    expected_value = np.dot(winnings, p)
    
    print(expected_value)

if __name__ == "__main__":
    solve()
```

---

## 🔬 Часть 6: Детальный разбор кода с NumPy

### Шаг 1: Считывание входных данных

```python
data = sys.stdin.read().split()
```

**Зачем так?**
- `sys.stdin.read()` читает **весь входной поток** целиком
- `.split()` разбивает текст по **любым пробельным символам** (пробелы, табуляции, переносы строк)
- Это **универсальный способ**, который работает независимо от того, как поданы данные:
  - В одну строку: `4 0.1 0.3 0.2 0.4`
  - В несколько строк:
    ```
    4
    0.1 0.3
    0.2 0.4
    ```

**Результат:** список строк `['4', '0.1', '0.3', '0.2', '0.4']`

### Шаг 2: Извлечение n и массива p

```python
n = int(data[0])
p = np.array(data[1:n+1], dtype=float)
```

- `data[0]` — это число `n` (количество возможных выигрышей)
- `data[1:n+1]` — это элементы массива `p` (вероятности)
- `np.array(..., dtype=float)` — преобразует список строк в **массив чисел с плавающей точкой**

**Результат:** массив `p = [0.1, 0.3, 0.2, 0.4]`

### Шаг 3: Создание массива выигрышей

```python
winnings = np.arange(n)
```

`np.arange(n)` создает массив целых чисел от 0 до n-1:

**Результат:** массив `winnings = [0, 1, 2, 3]`

### Шаг 4: Вычисление математического ожидания

```python
expected_value = np.dot(winnings, p)
```

`np.dot` вычисляет **скалярное произведение** двух векторов:

$$\text{dot}([0, 1, 2, 3], [0.1, 0.3, 0.2, 0.4]) = 0 \cdot 0.1 + 1 \cdot 0.3 + 2 \cdot 0.2 + 3 \cdot 0.4$$

**Как это работает под капотом:**
1. NumPy берет первый элемент из каждого массива: 0 × 0.1 = 0.0
2. Второй элемент: 1 × 0.3 = 0.3
3. Третий элемент: 2 × 0.2 = 0.4
4. Четвертый элемент: 3 × 0.4 = 1.2
5. Суммирует всё: 0.0 + 0.3 + 0.4 + 1.2 = 1.9

**Альтернативные способы:**
```python
# Способ 1: поэлементное умножение + сумма
expected_value = np.sum(winnings * p)

# Способ 2: через оператор @ (Python 3.5+)
expected_value = winnings @ p
```

Все три способа дают одинаковый результат!

---

## ⚠️ Часть 7: Подводные камни и частые ошибки

### Ошибка 1: Индексация с единицы

**Неправильно:**
```python
for i in range(1, n+1):  # ❌ Ошибка!
    expected_value += i * p[i-1]
```

**Почему это ошибка?**
В задаче сказано: "Коля может выиграть сумму от 0 до n-1". Значит, выигрыш **совпадает с индексом**:
- Индекс 0 → выигрыш 0
- Индекс 1 → выигрыш 1
- Индекс i → выигрыш i

**Правильно:**
```python
for i in range(n):  # ✅
    expected_value += i * p[i]
```

### Ошибка 2: Забывают про сумму вероятностей

В условии сказано: $\sum_{i=0}^{n-1} p_i = 1$. Это **обязательное условие** для вероятностей. Если сумма не равна 1, то это не распределение вероятностей, и формула матожидания не работает корректно.

В реальных задачах это условие всегда выполняется, но полезно помнить!

### Ошибка 3: Целочисленное деление

Если использовать обычный Python без NumPy, можно случайно получить целочисленное деление:

```python
# ❌ Опасно в Python 2
expected_value = sum(i * p[i] for i in range(n))
```

В Python 3 это работает корректно, но с NumPy лучше явно указывать `dtype=float`:

```python
p = np.array(data[1:n+1], dtype=float)  # ✅ Явно указываем тип
```

### Ошибка 4: Неправильный ввод данных

Если использовать `input().split()`, а данные поданы в несколько строк, программа упадет:

```python
# ❌ Работает только если всё в одной строке
n = int(input())
p = list(map(float, input().split()))
```

**Правильно:**
```python
# ✅ Работает с любым форматом ввода
data = sys.stdin.read().split()
n = int(data[0])
p = list(map(float, data[1:n+1]))
```


### Задача 3

Дана квадратная матрица A. Посчитайте произведение диагональных элементов матрицы, строго превосходящих среднее значение элементов всей матрицы.

Хинт: взять диагональ матрицы – np.diag(), произведение элементов массива – np.prod(), среднее значение в массиве – np.mean().

In [40]:
size = random.randint(2, 10)
matrix = np.random.randint(-100, 100, (size, size))
print(matrix)

# Диагональ
diag_A = np.diag(matrix)
print(diag_A)

# Среднее
mean_A = np.mean(matrix)
print(mean_A)

# Матрица из элементов сторого больше среднего
A = matrix[matrix > mean_A]
print(A)

answer = np.prod(A)
print(answer)

[[90  1]
 [83 79]]
[90 79]
63.25
[90 83 79]
590130


### Задача 4

Дано число n. Создайте матрицу A размера n×n такую, что A[i][j]=i*j. Нумерация строк и столбцов начинается с нуля.

In [ ]:
n = random.randint(2, 10)

A = np.outer(np.arange(n), np.arange(n))
# или A = np.arange(n)[:, None] * np.arange(n)[None, :]

print(A)

[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]
